# Generated by Django 4.0.6 on 2022-11-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='Expiry must be greater than or equal today',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
